import { useEffect, useState } from 'react';
import { motion, useReducedMotion } from 'framer-motion';
import {
  Sparkles, Layers, Cpu, Users, DollarSign, Network,
  Star, CheckCircle, Zap, BarChart2, Search, Share2,
  Code, User, AlertCircle, Link, Target
} from 'lucide-react';
import { cn } from '@/lib/utils';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import type { ContactIntel } from '@/data/contactIntel';

const ICON_MAP: Record<string, React.ElementType> = {
  Layers, Cpu, Users, DollarSign, Network, Star, CheckCircle,
  Zap, BarChart2, Search, Share2, Code, User, AlertCircle, Link, Target,
};

const CONFIDENCE_COLOR = {
  high: 'text-emerald-400 bg-emerald-500/10 border-emerald-500/20',
  medium: 'text-amber-400 bg-amber-500/10 border-amber-500/20',
  low: 'text-slate-400 bg-slate-500/10 border-slate-500/20',
};

interface AIInsightsCardProps {
  intel: ContactIntel;
  isAnalyzing?: boolean;
}

function TypingText({ text, speed = 18 }: { text: string; speed?: number }) {
  const [displayed, setDisplayed] = useState('');
  const prefersReduced = useReducedMotion();

  useEffect(() => {
    if (prefersReduced) {
      setDisplayed(text);
      return;
    }
    setDisplayed('');
    let i = 0;
    const interval = setInterval(() => {
      i++;
      setDisplayed(text.slice(0, i));
      if (i >= text.length) clearInterval(interval);
    }, speed);
    return () => clearInterval(interval);
  }, [text, speed, prefersReduced]);

  return <>{displayed}</>;
}

export function AIInsightsCard({ intel, isAnalyzing = false }: AIInsightsCardProps) {
  const prefersReduced = useReducedMotion();

  if (isAnalyzing) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>AI Insights</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-3">
            {[80, 65, 90, 72, 55].map((w, i) => (
              <div key={i} className="shimmer h-4 rounded-md" style={{ width: `${w}%` }} />
            ))}
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between gap-3 flex-wrap">
          <CardTitle>AI Insights</CardTitle>
          <div className="flex items-center gap-1.5 px-2 py-1 rounded-full bg-brand-600/15 border border-brand-500/25">
            <Sparkles className="w-3 h-3 text-brand-400" />
            <span className="text-[10px] text-brand-300 font-medium">Generated by RevenueOS AI</span>
          </div>
        </div>
      </CardHeader>
      <CardContent className="space-y-5">
        {/* Narrative */}
        <p className="text-[12px] text-slate-300 leading-relaxed">
          {prefersReduced ? intel.aiNarrative : <TypingText text={intel.aiNarrative} speed={12} />}
        </p>

        {/* Insight bullets */}
        <div className="space-y-2">
          {intel.aiInsights.map((insight, i) => {
            const Icon = ICON_MAP[insight.icon] ?? Sparkles;
            return (
              <motion.div
                key={insight.id}
                initial={{ opacity: 0, x: -8 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: prefersReduced ? 0 : 0.3 + i * 0.08 }}
                className="flex items-start gap-2.5 p-2.5 rounded-lg bg-white/[0.03] border border-white/[0.06]"
              >
                <div className="w-6 h-6 rounded-md flex items-center justify-center bg-brand-600/20 flex-shrink-0 mt-0.5">
                  <Icon className="w-3.5 h-3.5 text-brand-400" />
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-xs text-slate-300 leading-relaxed">{insight.text}</p>
                </div>
                <span className={cn('flex-shrink-0 text-[10px] px-1.5 py-0.5 rounded border font-medium', CONFIDENCE_COLOR[insight.confidence])}>
                  {insight.confidence}
                </span>
              </motion.div>
            );
          })}
        </div>

        {/* Talking points */}
        {intel.aiTalkingPoints.length > 0 && (
          <div>
            <p className="text-[10px] text-slate-500 uppercase tracking-wider mb-2">AI Talking Points</p>
            <div className="space-y-1.5">
              {intel.aiTalkingPoints.map((point, i) => (
                <div key={i} className="flex items-start gap-2">
                  <span className="w-4 h-4 rounded-full brand-gradient flex items-center justify-center text-[9px] text-white font-bold flex-shrink-0 mt-0.5">{i + 1}</span>
                  <p className="text-[11px] text-slate-400 leading-relaxed">{point}</p>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Recommended opener */}
        {intel.aiRecommendedOpener && (
          <div className="p-3 rounded-lg bg-brand-600/10 border border-brand-500/20">
            <p className="text-[10px] text-brand-400 uppercase tracking-wider mb-1.5 flex items-center gap-1">
              <Sparkles className="w-3 h-3" /> Recommended Opener
            </p>
            <p className="text-[11px] text-slate-300 leading-relaxed italic">"{intel.aiRecommendedOpener}"</p>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
